### ISSUE TITLE
[bug] Manifest URL changes

### ISSUE THREAD

**Issue by nstringham** [alexandrunastase/json-formatter-live#16]
On this line a version is appended to the end of the manifest URL
https://github.com/alexandrunastase/json-formatter-live/blob/43f4640c640e85e58024a52e44357915c580bd3e/src/routes/index.svelte#L56

This causes browsers to think that JSON formatter is an entirely different app every time the version changes

The standard advice has been to never change the manifest URL. However there is a new id field that could also work to solve this problem

**Comment by nstringham** [comment]
After reading the W3C spec more closely I realized that the current setup is actually spec compliant. Although it doesn't work in older browsers It does work in the latest version of Chrome and should work in future browser versions.

It would still probably be a good idea to make the manifest URL unchanging but it shouldn't be causing duplicate apps.

**Comment by alexandrunastase** [comment]
The reason I did it like this was because there were some issues in the past with the cache busting. While investigating this I actually found an issue with the cache busting. The solution is not super elegant, but at least the caching is working reliably now. I also found out there is an issue with the caching mechanism from netlify using etags : https://answers.netlify.com/t/netlify-ignores-cache-control-for-304/2912/26.

 I removed the query param and updated the headers that should be given from netlify for the manifest.json file. This should prevent any issues on older browsers. Anyway older browser are not a very big priority since this PWA stuff is pretty new anyway. Thanks for reporting the ticket :+1:
